fusion_classifier:
  _target_: src.modules.audio_vpc.RobustFusionClassifier
  audio_embedding_size: 192
  text_embedding_size: 768
  hidden_size: 512
  num_classes: ${datamodule.num_classes}
  norm_type: 'layer'
  accum_method: 'concat'
  dropout_audio: 0.3
  dropout_text: 0.1